BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILE_COLLECTIONS += "meta-sui-edge"
BBFILE_PATTERN_meta-sui-edge = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sui-edge = "6"

LAYERVERSION_meta-sui-edge = "1"
LAYERDEPENDS_meta-sui-edge = "core openembedded-layer"
LAYERSERIES_COMPAT_meta-sui-edge = "scarthgap"
