BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILE_COLLECTIONS += "meta-suifleet"
BBFILE_PATTERN_meta-suifleet = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-suifleet = "6"

LAYERVERSION_meta-suifleet = "1"
LAYERDEPENDS_meta-suifleet = "core openembedded-layer"
LAYERSERIES_COMPAT_meta-suifleet = "scarthgap"
